spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

aws:
  s3:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    AWS_S3_BUCKET_PROFILE_IMAGES: ${AWS_S3_BUCKET_PROFILE_IMAGES}
    AWS_S3_BUCKET_COLLECTION_IMAGES: ${AWS_S3_BUCKET_COLLECTION_IMAGES}
    AWS_S3_BUCKET_ITEM_IMAGES: ${AWS_S3_BUCKET_ITEM_IMAGES}

server:
  port: ${PORT:8080} # 👈 This is crucial for Heroku
  servlet:
    session:
      cookie:
        domain: .benlimpic.info # ✅ enables shared session across subdomains if needed
        same-site: none
        secure: true

app:
  base-url: https://shelved-demo-app.benlimpic.info
