spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  main:
    allow-circular-references: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

cloud:
  aws:
    s3:
      region:
        static: us-west-1
    buckets:
      AWS_S3_BUCKET_PROFILE_IMAGES: ${aws.s3.AWS_S3_BUCKET_PROFILE_IMAGES}
      AWS_S3_BUCKET_COLLECTION_IMAGES: ${aws.s3.AWS_S3_BUCKET_COLLECTION_IMAGES}
      AWS_S3_BUCKET_ITEM_IMAGES: ${aws.s3.AWS_S3_BUCKET_ITEM_IMAGES}

server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

logging:
  level:
    root: INFO
