spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  web:
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      enabled: true
      max-file-size: 4MB
      max-request-size: 4MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:9090}
  servlet:
    session:
      cookie:
        domain: benlimpic.info
        same-site: none
        secure: true

app:
  base-url: https://shelved-demo-app.benlimpic.info

aws:
  s3:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    AWS_S3_BUCKET_PROFILE_IMAGES: ${AWS_S3_BUCKET_PROFILE_IMAGES}
    AWS_S3_BUCKET_COLLECTION_IMAGES: ${AWS_S3_BUCKET_COLLECTION_IMAGES}
    AWS_S3_BUCKET_ITEM_IMAGES: ${AWS_S3_BUCKET_ITEM_IMAGES}
